"""Cass devices subcommand — list / revoke devices via portal API.

Device CREATION lives in the existing browser-loopback `cass login` flow
(cass/auth.py). Portal's /api/cli/login mints a per-device CF Access
service token + per-device mcp_key during the same redirect, and the
results land in ~/.cass/env via write_env_file() below.

This module just exposes:

    cass devices list             # GET portal /api/cli/devices
    cass devices status           # show env creds for THIS machine
    cass devices revoke <id>      # DELETE portal /api/cli/devices/:id
    cass devices logout           # remove ~/.cass/env (doesn't revoke)
"""

from __future__ import annotations

import os
import shlex
from pathlib import Path
from typing import TypedDict

import click
import httpx

from cass.config import get_portal_url

ENV_PATH = Path.home() / ".cass" / "env"


class _DeviceCreds(TypedDict):
    email: str
    device_name: str
    cf_access_client_id: str
    cf_access_client_secret: str
    mcp_key: str


def write_env_file(creds: _DeviceCreds) -> None:
    """Write ~/.cass/env (export statements). chmod 600. Idempotent."""
    ENV_PATH.parent.mkdir(parents=True, exist_ok=True)
    contents = (
        "# Generated by `cass login` — per-device credentials.\n"
        "# Source this in ~/.zprofile (or .bashrc / .profile) so cass picks it\n"
        "# up automatically. Plugin manifests reference ${user_config.mcpKey},\n"
        "# which `cass setup` writes into ~/.claude/settings.json with the\n"
        "# same value as $CASS_MCP_KEY here.\n"
        f"export CASS_EMAIL={shlex.quote(creds['email'])}\n"
        f"export CF_ACCESS_CLIENT_ID={shlex.quote(creds['cf_access_client_id'])}\n"
        f"export CF_ACCESS_CLIENT_SECRET={shlex.quote(creds['cf_access_client_secret'])}\n"
        f"export CASS_MCP_KEY={shlex.quote(creds['mcp_key'])}\n"
    )
    ENV_PATH.write_text(contents)
    ENV_PATH.chmod(0o600)


def ensure_zprofile_sources_env() -> bool:
    """Append `source ~/.cass/env` to ~/.zprofile if not already there.

    Returns True if it added the line. No-op if already present.
    """
    zprofile = Path.home() / ".zprofile"
    line = f"source {ENV_PATH}"
    if zprofile.exists():
        existing = zprofile.read_text()
        if str(ENV_PATH) in existing:
            return False
    with zprofile.open("a") as f:
        f.write(f"\n# Cassandra CLI — auto-loaded creds\n{line}\n")
    return True


def get_env_credentials() -> _DeviceCreds | None:
    """Read currently-loaded creds from env (set by sourcing ~/.cass/env)."""
    cid = os.environ.get("CF_ACCESS_CLIENT_ID", "")
    csec = os.environ.get("CF_ACCESS_CLIENT_SECRET", "")
    key = os.environ.get("CASS_MCP_KEY", "")
    email = os.environ.get("CASS_EMAIL", "")
    if not (cid and csec and key):
        return None
    return _DeviceCreds(
        email=email or "",
        device_name="",
        cf_access_client_id=cid,
        cf_access_client_secret=csec,
        mcp_key=key,
    )


def _portal_request(method: str, path: str, **kwargs) -> httpx.Response:
    """Call portal with the CF Access service-token headers from env."""
    creds = get_env_credentials()
    if not creds:
        raise click.ClickException(
            "No service-token credentials. Run `cass login` first to mint a "
            "per-device CF token.",
        )
    portal = get_portal_url()
    headers = {
        "CF-Access-Client-Id": creds["cf_access_client_id"],
        "CF-Access-Client-Secret": creds["cf_access_client_secret"],
        "Authorization": f"Bearer {creds['mcp_key']}",
        "Content-Type": "application/json",
    }
    return httpx.request(method, f"{portal}{path}", headers=headers, timeout=15, **kwargs)


@click.group()
def devices() -> None:
    """List and revoke devices authorized for this account."""


@devices.command("list")
def devices_list() -> None:
    """Show all devices authorized for this account."""
    resp = _portal_request("GET", "/api/cli/devices")
    if resp.status_code != 200:
        raise click.ClickException(f"portal returned {resp.status_code}: {resp.text[:200]}")
    rows = resp.json().get("devices", [])
    if not rows:
        click.echo("No devices authorized.")
        return
    click.echo(f"{'ID':14s}  {'NAME':25s}  CREATED")
    for r in rows:
        click.echo(f"{r['id']:14s}  {r['device_name']:25s}  {r['created_at']}")


@devices.command("status")
def devices_status() -> None:
    """Show the currently-loaded credentials on THIS device."""
    creds = get_env_credentials()
    if not creds:
        click.echo("No env credentials loaded. Run `cass login`, then "
                   "`source ~/.cass/env`.")
        raise SystemExit(1)
    email = creds["email"] or "(unknown — re-run cass login to set CASS_EMAIL)"
    click.echo(f"Email:        {email}")
    click.echo(f"CF token:     present")
    click.echo(f"MCP key:      {creds['mcp_key'][:16]}...")
    click.echo(f"Env file:     {ENV_PATH}")


@devices.command("logout")
@click.confirmation_option(
    prompt="Remove ~/.cass/env (token stays valid until you `cass devices revoke`)?",
)
def devices_logout() -> None:
    """Delete this device's local env file. Does NOT revoke the token."""
    if ENV_PATH.exists():
        ENV_PATH.unlink()
        click.echo(f"Removed {ENV_PATH}")
    else:
        click.echo(f"{ENV_PATH} doesn't exist.")


@devices.command("revoke")
@click.argument("device_id")
def devices_revoke(device_id: str) -> None:
    """Revoke a device by ID. Use `cass devices list` to find IDs."""
    resp = _portal_request("DELETE", f"/api/cli/devices/{device_id}")
    if resp.status_code != 200:
        raise click.ClickException(f"portal returned {resp.status_code}: {resp.text[:200]}")
    click.echo(f"Revoked {device_id}.")
