package auth

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type DeviceCreds struct {
	Email                string
	DeviceName           string
	CFAccessClientID     string
	CFAccessClientSecret string
	MCPKey               string
}

func EnvPath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".cass", "env")
}

func ZprofilePath() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".zprofile")
}

func Write(c DeviceCreds) error {
	p := EnvPath()
	if err := os.MkdirAll(filepath.Dir(p), 0o700); err != nil {
		return err
	}
	contents := fmt.Sprintf(`# Generated by `+"`cass login`"+` — per-device credentials.
# Source this in ~/.zprofile (or .bashrc / .profile) so cass picks it
# up automatically. Plugin manifests reference ${user_config.mcpKey},
# which `+"`cass setup`"+` writes into ~/.claude/settings.json with the
# same value as $CASS_MCP_KEY here.
export CASS_EMAIL=%s
export CF_ACCESS_CLIENT_ID=%s
export CF_ACCESS_CLIENT_SECRET=%s
export CASS_MCP_KEY=%s
`,
		shellQuote(c.Email),
		shellQuote(c.CFAccessClientID),
		shellQuote(c.CFAccessClientSecret),
		shellQuote(c.MCPKey),
	)
	return os.WriteFile(p, []byte(contents), 0o600)
}

func Read() (DeviceCreds, error) {
	data, err := os.ReadFile(EnvPath())
	if err != nil {
		return DeviceCreds{}, err
	}
	vars := map[string]string{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		line = strings.TrimPrefix(line, "export ")
		k, v, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		vars[strings.TrimSpace(k)] = shellUnquote(strings.TrimSpace(v))
	}
	c := DeviceCreds{
		Email:                vars["CASS_EMAIL"],
		CFAccessClientID:     vars["CF_ACCESS_CLIENT_ID"],
		CFAccessClientSecret: vars["CF_ACCESS_CLIENT_SECRET"],
		MCPKey:               vars["CASS_MCP_KEY"],
	}
	if c.MCPKey == "" {
		return c, errors.New("no credentials in env file")
	}
	return c, nil
}

func Remove() error {
	if err := os.Remove(EnvPath()); err != nil && !os.IsNotExist(err) {
		return err
	}
	return nil
}

// EnsureZprofileSources appends `source ~/.cass/env` to ~/.zprofile if not
// already there. Returns true if it added the line.
func EnsureZprofileSources() (bool, error) {
	envPath := EnvPath()
	zp := ZprofilePath()
	if data, err := os.ReadFile(zp); err == nil {
		if strings.Contains(string(data), envPath) {
			return false, nil
		}
	}
	f, err := os.OpenFile(zp, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return false, err
	}
	defer f.Close()
	_, err = fmt.Fprintf(f, "\n# Cassandra CLI — auto-loaded creds\nsource %s\n", envPath)
	if err != nil {
		return false, err
	}
	return true, nil
}

// shellQuote matches Python shlex.quote — unquoted if safe, else single-quoted
// with embedded single quotes escaped as '"'"'.
func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	const safe = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789@%+=:,./-_"
	allSafe := true
	for _, r := range s {
		if !strings.ContainsRune(safe, r) {
			allSafe = false
			break
		}
	}
	if allSafe {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'"'"'`) + "'"
}

func shellUnquote(s string) string {
	if len(s) < 2 {
		return s
	}
	if s[0] == '\'' && s[len(s)-1] == '\'' {
		return strings.ReplaceAll(s[1:len(s)-1], `'"'"'`, "'")
	}
	if s[0] == '"' && s[len(s)-1] == '"' {
		return s[1 : len(s)-1]
	}
	return s
}
